name: ecom-github-actions
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # checking out the code first
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: build frontend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-frontend:latest ecom/frontend/ecommerce
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-frontend:latest

      - name: build backend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-backend:latest ecom/backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-backend:latest
